// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayftvexwjcarollvwunn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZnR2ZXh3amNhcm9sbHZ3dW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTczNTIsImV4cCI6MjA2MDgzMzM1Mn0.--vId-EZi7Zl1K4-csYdxtacpqCVwM7zhf57GYedlHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);